MunGell/awesome-for-beginners

README.md
https://github.com/tastejs/todomvc/labels/first%20time%20contributor
=> Add TodoMVC

README.md
=> Add neovim entry-level

README.md
https://github.com/mitmproxy/mitmproxy/labels/good%20first%20contribution
=> Add mitmproxy

README.md
A Python toolkit to build HTTP (micro)services
=> Add the Cliquet project

README.md
A lightweight JSON storage service with synchronisation and sharing abilities.
http://kinto.readthedocs.org/
=> Add the kinto project as awesome for beginners.

README.md
An attempt to add description for projects.
=> Add description to projects (fixes #8)

README.md
Added the [Kinto.js project](https://github.com/Kinto/kinto.js).
=> Add Kinto.js

README.md
=> Add Rust section, with Servo

README.md
The project TEAMMATES is added for beginners and the new category "Java" is created. Thank you for your consideration.
=> Add TEAMMATES under the new category: Java

README.md
Adds FreeCodeCamp to JavaScript category.
=> Add FreeCodeCamp to JavaScript list

README.md
Our project aims to assist newcomers to open-source with Git and making easy & important contributions. We use the "beginner" label to specify such issues. This commit adds our repository to the list.
=> Adds Goby to Ruby list

README.md
Low hanging fruits on Julia lang
=> Added the PR friendly Julians

README.md
Found a simple, beginner friendly JS date library called moment.js!
Hope this helps :D
=> Add Moment.js

README.md
Added to the JavaScript category
=> Add Serverless

README.md
Added Hoodie Camp to the list under Javascript Category
=> Added Hoodie Camp to the list under Javascript Category

README.md
Another project in Go with suitable issues for beginners.
=> Added Hugo - static site generator

README.md
Added TypeScript Category and TypeScript itself to its Category
=> Add new Category: TypeScript

README.md
=> Add Next.js

README.md
=> updated PR for repo standards

README.md
=> Added Visual Studio Code

README.md
@MunGell Although the label is quite different, i check the content and it is a beginner-friendly. Any thoughts? :)
Thanks
=> Added tensorflow

README.md
Reapp is pretty dead, their site & demos don't work. React Router never has anything beginner-friendly afaik.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mungell/awesome-for-beginners/72)
=> Removed dead/useless links

README.md
I fixed the tag format of Hugo to italic.
=> Fix Hugo tag format to italic

README.md
=> Added Helm

README.md
We at [coala](https://coala.io) are always striving to help newcomers get started with their first open source contribution!
P.S. we have an awesome hand-written guide at https://coala.io/newcomer, would it be okay to add that link in the description?
=> Add coala - an unified linting tool

README.md
This PR adds [JabRef](https://github.com/JabRef/jabref/labels/beginner).
I am highlighting the special "features" of beginner friendliness in the text
- Usage of tools to ensure code quality
- Code review by two developers
=> Add JabRef

README.md
[New Link](https://github.com/electron/electron/labels/help%2Fbeginner)
=> Change label for electron project to help/beginner

README.md
=> remove dupe mitmproxy

README.md
=> Added PublicLab.org (ruby on rails) to README

README.md
=> Add OrgManager

README.md
=> Rename Docker to Moby

README.md
Added Pybee/voc to Python section
=> Add Pybee/voc to Python section

README.md
Project link and label updated.
=> Update README.md Yarn Project

README.md
=> Add gratipay.com

README.md
I added https://github.com/stryker-mutator/stryker to JavaScript section
=> Added Stryker mutation testing framework to JavaScript section

README.md
Pytest have an easy tag for beginners (you can see the meaning of the easy tag explained in the pytest wiki page here https://github.com/pytest-dev/pytest/wiki/Europython-2015-sprints
=> Added Pytest to python section

CONTRIBUTING.md
Just one character, but more grammatical this way.
=> its is possessive (not it's, which is a contraction)

README.md
Added the awesome beginner friendly JavaScript and Go repos from the [DAV Foundation](dav.network)
=> added js and go repos from dav foundation

README.md
=> Added PHP Censor.

README.md
Nvim now uses the label "good first issue".
=> Updated Link/Label of Nvim

README.md
As with #154, Next.js was also updated to reflect some new focuses from GitHub. 🙌
=> Update Next.js label

README.md
=> Add Kap to JavaScript list

README.md
=> Add more advice for beginners.

README.md
add more project for Elixir programming language
=> add projects for Elixir

README.md
=> Add cookiecuttor to Python list

README.md
See: https://gratipay.news/the-end-cbfba8f50981
=> Remove gratipay, which is shutting down.

README.md
PS: you asked that the entries be added to the end. I know this is going to cause merge conflicts...
=> Add Concept to Clinic

README.md
This PR adds Reddit Enhancement Suite (RES) to the JavaScript List. RES has a very active group of contributors and has over 3 million users. It is easy to get started and yet a very meaningful project to be working on.
=> Add Reddit Enhancement Suite to JS List

README.md
Changed Ghost javascript label to `good first issue`
=> Changed JavaScript Ghost label

README.md
I noticed the original link was broken, looked into this further and corrected.
=> edited Sinatra URL

README.md
Also some linebreak updates for the Typescript repos.
=> Adds TSLint to the list of Typescript repos

README.md
Adding the Brave Browser project repo under the Javascript section.
=> Add the Brave Browser

README.md
=> rectified scrapy label

README.md
Added Node.js core under the JavaScript section
=> Added Node.js core

README.md
=> updated readme file (#192)

README.md
We don't use GitHub issues so we shy away from the norm a bit here but hopefully that's not a hard requirement.
=> Added Discourse

README.md
"low hanging fruit" label is used in zero tasks
"good first task" is actually used in many tasks in elasticsearch repo
=> Fixed elasticsearch label for newcomers

README.md
Vue (pronounced /vjuː/, like view) is a progressive framework for building user interfaces. Unlike other monolithic frameworks, Vue is designed from the ground up to be incrementally adoptable.
=> Add Vue.js The Progressive JavaScript Framework.

README.md
* added missing `_` for django cookiecutter
* removed trailing `_` for operationcode
=> Fix 2 incorrect '_'s

README.md
Jest link is broken due to the 👋 icon position is in the beginning and not the end
=> fixed jest link

README.md
Label "easyfix" definition:
> This issue is considered easy to fix by aspiring contributors.
=> Add Ansible, Simple IT Automation

README.md
Easy PRs are currently labeled with `status: easy`, not `easy`.
=> Update beginner label for pytest

README.md
Wanted to add my project Check It Out, been adding smaller issues and labeling them for beginners. Thanks!
=> Add Check It Out to Javascript projects

README.md
Hi, I'd like to add my project, which became pretty popular recently. We're looking mainly for bugfixes and new features, all contributions are reviewed and welcome.
=> Add nuclear to javascript category

README.md
I'm one of the primary maintainers of Squirrelly, and I can verify that it has the 'good first issue' label.
=> Add SquirrellyJS

README.md
Changed the `brave-laptop` reference (as the repo is now read-only) and changed it into `brave-browser` which now contains the current code-base.
Fixes #325
=> Changed brave-laptop to brave-browser.

README.md
super keen on new contributors for a 2 week old repository
=> add md-page to Javascript

README.md
Change label from `for-new-contributors` to `good first issue`.
=> Update Botpress label

README.md
Thanks for a great repository! 
Mattermost recently updated labels and so I'm submitting a PR to update the queries accordingly.
If any questions, let me know!
=> Update Mattermost entries for Go and JavaScript

README.md
=> Remove TSLint

README.md
https://github.com/MunGell/awesome-for-beginners/issues/360
=> Remove OperationCode

README.md
=> Add Hexagon project

CONTRIBUTING.md
=> Improved grammar in CONTRIBUTING.md file

README.md
=> Add mygpo.

README.md
=> Remove FirstPR

README.md
=> Add Drupal to list of PHP projects

README.md
=> Add hyper and nushell for Rust

README.md
Added `tree-sitter-legesher-python` project to Python section. Text editor also removed trailing whitespace from another submission. [Link for maintainer confirmation on label](https://github.com/legesher/tree-sitter-legesher-python/issues/12#issue-498907502)
```
```
```
```
=> Added tree-sitter-legesher-python project to Python section

README.md
The project "serverless"  changed the label to "good first issue".
=> Suggestion to update the README.md repository description

README.md
=> Add Babel to README.md

README.md
=> add mocha to readme

README.md
=> add React-content-loader

README.md
=> Add Laravel newsletter

README.md
=> add netlify-cms

README.md
Add Chatwoot to ruby
```
```
```
```
=> Add Chatwoot to ruby

README.md
=> Added altair to README

README.md
=> Add python-ds under Python

README.md
Hi there!
I've created a C# category and added two active projects with beginner-friendly labels.
Some HTML was necessary in order to get the cross-reference working.
=> added C# category with two projects

CONTRIBUTING.md
=> Updated a sentence

README.md
*Video Hub App* is an (MIT) open source Angular & Electron app for browsing videos on your computer. It compiles to Windows, Mac, and Linux.
It is actively developed and has hundreds of users.
Thank you for your consideration 🙇
=> Add Video Hub App to JavaScript list

README.md
=> Ruby on rails added

README.md
=> Add reatom

README.md
This repository contains the pseudocodes of various algorithms and data structures necessary for Interview Preparation and Competitive Programming. The choice of the programming language isn't a barrier as you need to write the code in plain English, focusing on the concepts of the question rather than the clutter of specific programming languages.
```
```
```
```
**Note** : …
=> Add Algorithmic Pseudocode (LaTex) to the list

README.md
=> READNE.md file updated

README.md
As seen in https://en.wikipedia.org/wiki/LaTeX , for eg..
```
```
```
```
=> Correctly capitalize LaTeX

.github/pull_request_template.md
=> Updated Sentence

README.md
=> Add Terraform Project

README.md
```
```
```
```
Hello I created this project and made many issues for hacktoberfest participants.
I'll improve this project and make issues more and more.
I don't have own community for this repository.
But game-of-life has huge community!
In this case, can I add this project??
Thank you :)
=> Add game-of-life repository

README.md
=> Add faker-ruby to the list

README.md
https://AncientBeast.com
- [ x ] I've read [contributing guidelines](https://github.com/MunGell/awesome-for-beginners/blob/master/CONTRIBUTING.md)
- [ x ] This PR does not introduce duplicates to the list
- [ x ] The link is added at the bottom of the list category
- [ x ] Suggested repository is maintained, have active community, is able to mentor new contributors and have issues with the suggested label
- [ x ] The link I add follows the suggested pattern:
```
```
```
- [awesome-for-beginners](https://github.com/MunGell/awesome-for-beginners/labels/good-first-contribu …
```
=> added Ancient Beast to the list

README.md
Updated link to redirect to the help wanted label instead to good first issue (because that label doesn't exist).
=> Changed mitmproxy's link and label comment to 'help wanted' from 'good first issue'.

README.md
=> Add Swift category by adding OpenFoodFacts-iOS

README.md
This repository has been archived by the owner. It is now read-only.
```
```
```
```
=> catapult has been archived

README.md
=> Added NextCloud Server to the PHP Category

README.md
```
- [Binari](https://github.com/BrandonArmand/Binari/issues?q=is%3Aissue+is%3Aopen+label%3A%22up+for+grabs%22) _(label: up for grabs)_ <br> Interactive code editor with a live binary tree visual designed to teach new developers the fundementals of dynamic programming.
```
```
```
=> Added Binari

README.md
=> Add RawCMS C# Project

README.md
=> Added ramda-adjunct to JavaScript section

README.md
Repository is already archived, just cleaning up.
=> Remove Operation Code, repository is already archived

README.md
- [X Suggested repository is maintained, have active community, is able to mentor new contributors and have issues with the suggested label
```
```
```
```
=> Add 'script' Go library

README.md
=> Add PrestaShop to PHP section

README.md
=> Adding "images to PDF" to java section

README.md
4Please complete the following checklist if your PR is adding new link to the list:
- [+] I've read [contributing guidelines](https://github.com/MunGell/awesome-for-beginners/blob/master/CONTRIBUTING.md)
- [+] This PR does not introduce duplicates to the list
- [+] The link is added at the bottom of the list category
- [+] Suggested repository is maintained, have active community, is able to mentor new contributors and have issues with the suggested label
- [+] The link I add follows the suggested pattern:
```
```
```
- [awesome-for-beginners](https://github.com/MunGell/awesome-for-beginners/labels/good-first-contribution) _(label: …
```
=> Two new libraries for data analysis and visualisation in python.md

README.md
```
```
```
- [Kinto.sh](https://github.com/rbreaves/kinto/labels/first-timers-only) _(label: first-timers-only)_ <br> Make Linux & Windows type like a mac.
```
=> Add Kinto.sh

README.md
=> Add Presto

README.md
```
```
```
- [json-editor](https://github.com/json-editor/json-editor/labels/good%20first%20issue) _(label: good first issue)_ <br>
JSON Schema Based Editor. JSON Editor takes a JSON Schema and uses it to generate an HTML form. It has full support for JSON Schema version 3 and 4 and can integrate with several popular CSS frameworks (bootstrap, spectre, tailwind).
```
=> Add json-editor (javascript)

README.md
=> Add yugabyte, distributed C++ database

README.md
- [ X] I've read [contributing guidelines](https://github.com/MunGell/awesome-for-beginners/blob/master/CONTRIBUTING.md)
- [ X] This PR does not introduce duplicates to the list
- [ X] The link is added at the bottom of the list category
- [ X] Suggested repository is maintained, have active community, is able to mentor new contributors and have issues with the suggested label
```
```
```
- [awesome-for-beginners](https://github.com/MunGell/awesome-for-beginners/labels/good-first-contribution) _(label: good-first-contribution)_ <br> A list of awesome beginners-friendly …
```
=> Add ArviZ to list

README.md
=> Add ealush/vest

README.md
=> Added reactjs.org

README.md
=> adding Habitica to the list

README.md
- Hoppscotch is an API request builder
- Web app: https://hoppscotch.io
- GitHub: https://github.com/hoppscotch/hoppscotch
```
```
```
```
=> Adds Hoppscotch to JavaScript category

README.md
I added a new repository to a new category (CSS)
```
```
```
```
=> Added sButtons repository

README.md
```
```
```
```
Hey @MunGell,
just adding cypress test runner in.
Cheers
=> Adding cypress test runner lib

README.md
=> Fix link to Rustfmt issues

README.md
This PR, Includes MindsDB to the Python list.
```
```
```
```
=> Add MindsDB 

README.md
=> Adding Flarum in PHP section

README.md
Hey @MunGell 
I've got some great repos of the VueJS ecosystem. All maintained and good starting points 💪️
Cheers,
Peter
```
```
```
```
=> Adding three libraries from the Vue-ecosystem in

README.md
=> Adding LitmusChaos to the TypeScript good-first-issue list

README.md
Added [Graphback](https://graphback.dev/) 
```
```
```
```
=> Add Graphback

README.md
I have fixed a little typo!
PS learning how to make pull requests
```
=> fixed typo now

README.md
=> Adding Time to Leave to Javascript

README.md
=> Spelling changes and programming language name changes

README.md
=> Added Meteor to JavaScript section

README.md
=> Add bokeh to python projects

README.md
PR does not add a new list, just updates an issue label for keystone.js
=> chore: update keystonejs label

README.md
Current link has no results. The easy label was changed to the update I wrote.
=> Update TiKV link to the new label

README.md
SymPy is a Python library for symbolic computations.
```
```
```
```
=> Add SymPy to Python projects

README.md
It appears one project I was interested in has been archived. I have removed it from the list.
=> Removed entry for archived project python-ds

README.md
Hey @MunGell 
webdriver.io sounds like a good candidate.
Cheers,
Peter
```
```
```
```
=> Adding webdriver.io

README.md
Proposing my own project https://github.com/LouisCAD/kotlin-libraries-playground
Specially designed for beginners!
```
```
```
```
=> ✚ Kotlin-libraries-playground

README.md
=> Add grok.net to C# projects

README.md
PureLB is a load-balancer orchestrator for Kubernetes. It uses
standard Linux networking and routing protocols, and works with the
operating system to announce service addresses. It's written in Go.
We welcome contributions and use the "GoodFirstIssue" label.
```
```
```
```
=> Add PureLB to the Go section

README.md
=> Added swag-for-dev suggestion under Javascript category 

README.md
=> Add matestack to Ruby projects

README.md
I dont know if there is space for small projects, thanks anyway!
```
```
```
```
=> Add Sorting Algorithms Visualizer in python section

README.md
=> Add dotenv-linter

README.md
=> Added pytorch

README.md
=> Booster added to typescript projects

README.md
Removed the unnecessary comma in README.md.
=> Fixed #897, Modified README.md

README.md
[MediaWiki](https://www.mediawiki.org/wiki/MediaWiki) is a free and open-source wiki software package.  It powers [Wikipedia](https://www.wikipedia.org/) and is largely written in PHP. 
```
```
```
```
=> Add MediaWiki to PHP Projects

README.md
=> Added Meshery as a Golang Project

README.md
```
```
Cake (C# Make) is a free and open source cross-platform build automation system with a C# DSL for tasks such as compiling code, copying files and folders, running unit tests, compressing files and building NuGet packages.
https://cakebuild.net
=> Add Cake build project

README.md
https://github.com/prestosql/presto/ redirects
https://github.com/trinodb/trino
- ~The link is added at the bottom of the list category~ (it's an update)
```
```
```
```
=> Update the project name to Trino

README.md
In the Brave Browser project the label is no more `good-first-bug`. 
They adapted `good-first-issue`
=> Update link for "Brave Browser" project in README.md

README.md
Tag changed from " first-timer-only" to "good first issue".
=> In C++ category - MoveIt - tag name changed

README.md
=> Add Example Link: Create React App

README.md
Merge Conflict resolution for #938
=> Sir noob97/master

README.md
[ReactiveSearch](https://github.com/appbaseio/reactivesearch) is an Apache 2.0 licensed UI components library for Elasticsearch - available for React, Vue and React Native.
```
```
```
```
=> Add ReactiveSearch to JavaScript projects

README.md
=> Add Veloren to Rust section

README.md
```
```
```
```
[Here is the proposal to the project maintainers.](https://github.com/pharo-project/pharo/issues/9253)
=> Add Pharo and new section dedicated to Smalltalk

README.md
=> Added Codename One in Java

data.json
Adding https://github.com/h2oai/wave.
=> Add H2O Wave

data.json
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1tRng3ur1Fwzc9YAhhsHC8IgkXSm7nc2A%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=lf5BMiQ)
Adding https://github.com/ntedgi/node-efficientnet
=> Add EfficientNet - image recognition model for node js

data.json
Add Exosphere and two new technologies, Elm and Ansible.
=> Add Exosphere

data.json
Signed-off-by: Gaius <gaius.qi@gmail.com>
=> feat: add dragonfly to golang projects

README.md
PR is a good acronym but should not be in the title due to inaccessibility for new programmers. When I landed on this page I had no idea what PR meant and it seemed very strange to use an acronym in the title of something targeted at beginners.
=> Unclear to beginners what PR stands for

data.json
If anyone is interested, there is a cool project like this
=> Adding HMPL.js

data.json
We at Multiwoven are creating an open-source reverse ETL platform for Data Activation.
=> Add Multiwoven in Ruby section

data.json
The game-of-life repository has been archived
=> Removed game-of-life from List

data.json
=> fix: neovim good first issue

data.json
cdnjs is now robot-only repository for cdnjs, now pull requests are no longer accepted for this repository.
=> Deletion of the cdnjs project, because it is now a robot-only repository 

data.json
=> Visual Studio Code

data.json
H2O Wave apps is looking for contributors.
=> Add H2O Wave apps

data.json
[Kanister](https://github.com/kanisterio/kanister) is an open source data protection workflow engine, by [Kasten](https://www.kasten.io/). It is written in Go. The team has seen a steady growth in adoption, and will like to share it with folks who are interested in contributing their first PR.
Check out Kanister's [CONTRIBUTING.md](https://github.com/kanisterio/kanister/blob/master/CONTRIBUTING.md) and [CODE_OF_CONDUCT.md](https://github.com/kanisterio/kanister/blob/master/CODE_OF_CONDUCT.md) to learn more. Feel free to join us on [Slack](kanisterio.slack.com) for upcoming features.
=> Add Kanister to the list

data.json
Added FreshRSS to the list.
Website: https://freshrss.org/
Repository: https://github.com/FreshRSS/FreshRSS
FreshRSS is a self-hosted RSS and Atom feed aggregator.
It is lightweight, easy to work with, powerful, and customizable. 
Languages:
- Backend: PHP
- Frontend: plain JavaScript, CSS
Our `good first issue` tickets: https://github.com/FreshRSS/FreshRSS/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
=> Add FreshRSS to data.json (PHP project, Open Source Reader. Since 2012)

data.json
Croma is a open source app which is build using react native. It is build for graphics designers.
=> Add croma - An open source react native app for web, iOS and android for color palette management

data.json
OMRChecker helps to grade exams fast and accurately using a scanner 🖨 or your phone 🤳. Learn image processing with Python and OpenCV while contributing to one of the most popular repositories related to OMR topic on github.
=> Add OMRChecker

data.json
Adding my iOS app called "Basic Car Maintenance" it's open  source for Hacktoberfest and beyond
=> Add Basic Car Maintenance iOS app

CONTRIBUTING.md
because clear and error-free communication is essential for effective learning and comprehension.
=> "I fixed a typo in the second point, making it more beginner-friendly."

data.json
Updating the database with Embedchain github repo: 
- Embedchain - 3.9K stars
- It helps create ChatGPT like bots with only a few lines of Code.
- Repo Link: https://github.com/embedchain/embedchain
Has issues labelled as good-first-issue
And is maintained actively and has an active community of contributors with growing repos
=> update: Python with Embedchain(good-first-issue)

data.json
Added [Impler](https://github.com/implerhq/impler.io) to the list - Impler is a readymade spreadsheet import experience for products to save cost and onboard customer data faster.
The project has 65+ stars, documentation, changelog, website, good-first-issues, a CONTRIBUTING.md file, well-written documentation for development and contribution, and is actively maintained.
Thanks in advance!
=> Add Impler.io

data.json
More info about F3D: https://f3d.app
=> Add F3D to C++ projects

data.json
[activist](https://github.com/activist-org/activist) is a network for political action empowering individual to collaborate on issues that matter to them.
=> Add activist to data.json

CONTRIBUTING.md
Revised sentences to enhance readability and understanding.
=>  Improve Sentence Structure in Contribution Guidelines

data.json
Adds a new project: [LinksHub](https://github.com/rupali-codes/LinksHub)
Under `Typescript` category.
=> feat(new project): add new project LinksHub

README.md, data.json
miniob is a database implementation learning system which written in C++ and it has a lot of features to implenment.
=> add miniob in C++ section

data.json
Hey @MunGell, thanks for having created this awesome list, I think it's a very good way for newcomers to approach programming.
With this PR I added [Sniffnet](https://sniffnet.net) to the list of Rust repositories that can benefit from beginners contributions.
=> Added Sniffnet to Rust resources

data.json
This repository has been archived
=> Removed LightTable from data.json

data.json
This repository hasn't been updated in a year
=> Removed SiriXDB from data.json

data.json
This repository has been inactive for two years
=> Removed Kotlin Libraries Playground from data.json

data.json
This repository has been inactive for 9 months
=> Removed md-page from data.json

data.json
Matestack hasn't had a commit for 2 years.
Also fixed minor issue with list in Harmony entry
=> Removed MateStack for being inactive

data.json
I am the core maintainer of this library.
=> added utils library under go category

data.json
This repo has been inactive for 8 months.
=> Remove Kap for inactivity

data.json
This repository has been inactive for 5 years
=> Removed  JARVIS-on-Messenger from data.json

data.json
Removed for inactivity (> 2 years)
=> Remove SimplQ from data.json

data.json
This repository has been inactive for 9 months
=> Removed kinto.sh from data.json

data.json
This repository has been inactive for 2 years
=> Remove Goby from data.json

data.json
this repo has been archived, it's been moved to a different repo, and now uses Flutter, I didn't add the new one, because I don't maintain it, but here's the link, I can add it if you like
https://github.com/openfoodfacts/smooth-app
=> Remove OpenFoodFacts

data.json
Over a year of inactivity in this repo
=> Remove React Help Create for inactivity

data.json
This repo seems reasonably active, is in Kotlin so quite beginner friendly and has multiple `good first issue` labelled issues.
=> Added OpenCalc to data.json

data.json
This repository has been inactive for over a year
=> Remove create aio app

data.json
=> add Rawsec Cybersecurity Inventory

data.json
The repository has been moved, information has been updated.
=> Update HMPL data

data.json
See the discussion behind this in the conversation of #1390.
=> Added harmony competition to description in data.json

data.json
This reimplements #1297 as I wasn't allowed to fix merge conflicts on that pull request.
=> (Reimplements #1297) Add zoom-rs to README.md data.json

data.json
This pull request adds FastAPI-related content to the JSON file. If you have time, please review it and merge it afterward.
Thank you!
=> Add fastAPI to data.json

data.json
=> Removed Letra Extension for inactivity

data.json
This repo has been inactive for over 2 years
=> Remove Algorithmic Pseudocode from data.json

data.json
A .NET library that makes it easier to create beautiful console applications.
=> Added Spectre.Console

data.json
=> Add TensorZero to data.json

data.json
Due to slight inactivity but also no appropriately labelled issues.
=> Remove faker from the data.json

.github/scripts/render-readme.py
A little formatting and the movement of the definition of a new technology dictionary into a function.
=> Minor improvements to the readme generation workflow

data.json
Android keyboards for language learners with translation, verb conjugation and more!
good first issues https://github.com/scribe-org/Scribe-Android/issues?q=sort%3Aupdated-desc+is%3Aopen+label%3A%22good+first+issue%22
=> add Scribe-Android

.github/README-template.j2
This will hopefully help those who come to this list but don't actually know how to contribute using git and github.
=> Added a sentence linking to the First Contributions repository

data.json
Metabase is a business intelligence platform for visualising and analysing data.
[good first issues](https://github.com/metabase/metabase/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22good%20first%20issue%22)
=> add metabase to clojure projects

data.json
- Moved Yarn link to Berry (Yarn's active development branch),
- Also changed the name so people don't get confused if they click on it,
- Added TypeScript to the technologies.
=> Updates to the Yarn entry.

data.json
Adds [CatimaLoyalty/Android](https://github.com/CatimaLoyalty/Android).
This repository is active and has a number of appropriately labelled issues.
=> Added Catima entry to the data.json

data.json
Readest is a modern, feature-rich ebook reader designed for avid readers offering seamless cross-platform access, powerful tools, and an intuitive interface. Being actively developed it has a beginner-friendly community.
=> Add Readest to data.json

data.json
See commit comments for individual changes and justifications.
=> Various cleanup changes to the data.json

data.json
The repository has had no commits since Novemeber 2023.
=> Removed Images To PDF from the data.json

README.md, data.json
- Added PyMC, a Python library for Bayesian statistical modeling and probabilistic machine learning.
- The repository is actively maintained and includes 'good first issue' labels for beginners.
- It provides a supportive community and clear contribution guidelines, making it an excellent addition for new contributors.
=> Added PyMC to Python category in Awesome for Beginners

data.json
The repository has had no commits since August 2023.
=> Removed SirixDB from the data.json for inactivity

data.json
This repo appears reasonably active and has lots of appropriately labelled issues
=> Add ImprovedTube's repository to the list

data.json
There have been no commits since last October and very few since the October before that.
=> Remove httpexpect from the data.json for inactivity

data.json
Fixed typo in descriptions for 
- HueHive
- Manifest
- reactjs.org
=> Fix typos in data.son

data.json
This repository has been inactive for 6 years!
=> Removed Tessel 2 CLI from the data.json for inactivity

.github/README-template.j2
This is as I failed to persist the changes made in #1019 when I moved to using a template (#1513).
=> Set main heading in README-template.j2 from PR to Pull Request

data.json
There is no commit for this project since Jun 26, 2023. Remove inactive project from data.json
=> Remove Node Efficientnet from data.json for inactivity

data.json
Add `Python` as one of the major technologies used in www.devopness.com repository, as can be seen in https://github.com/devopness/devopness:
This improves the works started on #1565 as the repo was not using Python at the time #1565 was merged. Also updates repo description, for easier understanding.
=> feat: add Python language to `Devopness` repo

data.json
project's last commit is 4 years ago and it seems it's not active anymore.
=> Remove Iron from data.json because of inactivity

CONTRIBUTING.md
This takes a number of suggested changes (#1564, #1572, #1586), combining parts from them to make this improvement to the guide.
Many thanks to @hendhamdi, @Shadowrithik and @omsudhamsh.
Closes #1563
=> Improve the Contribution Guide with input from several people

data.json
I didn't fix much grammar, as most of the grammatical errors seem to be true to the projects own descriptions on GitHub.
=> Minorly fix spelling and grammar in the descriptions in data.json

data.json
Added a new project(Supabase) to the data.json list.
=> Add Supabase to the list of repositories with a description and link

data.json
This repo has not had a commit for 7 months
=> Remove Semantic-UI-React from the data.json for inactivty

data.json
This project is highly active on Github and all the issues in the curriculum repository are beginner friendly. The community is friendly and willing to help new contributors to get involved.
=> Add The Odin Project to the open source project list

data.json
This repo has not had a commit for about 5 years
=> Remove Strongbox from data.json for inactivity
