MunGell/awesome-for-beginners

README.md
Updates the repository list to use the correct label for the TensorFlow repo, `stat:contributions welcome`.
=> Fixed the label for the TensorFlow repository

README.md
The correct label is `difficulty/low` instead `easy`.
=> Fix Python Babel label

README.md
Most Chef projects have the "Type: Jump In" label, so add the two major ones.
=> Add Chef and Ohai to ruby projects

README.md
Right now no change cosmetically because github's md viewer seems to do OK with an unpaired one, but this avoids the possibility someone might inadvertantly create italics down the road.
=> Fixed the unpaired asterisk

README.md
Fixed Electron's beginner label. Initially it was under C++ but most of it is Javascript/Node.JS so moved it under Javascript.
=> Fix Electron label and move it under Javascript

README.md
I saw following popup on JabRef's GitHub repository:
Google did not find more about this movement, but I followed the suggestion by GitHub and renamed "beginner" to "good first issue". Thus, I also renamed it here.
=> Rename "beginner" to "good first issue"

README.md
I was looking for things to work on and noticed that this link for Hyper didn't reflect the correct name of the label for beginners working on first issues.
=> Update label and link for Hyper

README.md
Label: good first issue and label:help wanted are now used instead on the vs code repository
=> Update VS code link

README.md
This PR fixes incorrect links for mission-control and captain.
The issue was:
- The links for mission-control and captain were swapped.
- Clicking mission-control directed to captain's repo and vice versa.
Solution:
- Swapped the two links around.
- Checked proper behaviour on remote branch.
Additionally:
- It removes two instances of trailing whitespace
=> Fix swapped links for mission-control and captain.

README.md
The links to the Julia Intro issue and Up for grabs labels show zero entries. 
The labels Julia uses are now help wanted and good first issue.
This is stated on a note on the issue table.
=> Change the Links to the Julia Issues

README.md
The current playframework link show 0 entries,
the repo uses "good first issue" now, multiple issues there
=> update play framework link

README.md
[rustfmt](https://github.com/rust-lang-nursery/rustfmt) There are no issues for `easy` label so I changed the link to `good-first-issue` label.
[rust-clippy](https://github.com/rust-lang-nursery/rust-clippy) There are no issues for `E-easy` label so I changed the link to `good first issue` label
=> Changed link for rustfmt and rust-clippy

README.md
There are no issues for easy-fix label for the Leaflet repository, so I changed the link to the good first issue label where I think there are some doable issues for beginners to open source.
=> Changed link for Leaflet

README.md
The TypeScript label wasn't directing to the correct label
=> Fix TypeScript link to GitHub repository

README.md
I added two entries of the same project, one for Go and one for Javascript
(Both links point to different filters in github, so they point to
the specific list of issues for each language).
I can confirm (as part of the core team) that the labels are appropriate for
beginners, the project is maintained, and they will be really welcome :)
This would replace the #146 PR
=> Add Mattermost "Up for graps" + "Introductory" for Go and Javascript

README.md
Changed the name Piwik to Matomo as requested.
The pull request #193 seems to be dead.
=> Piwik is now Matomo

README.md
Unfortunately, qutebrowser is growing into a more and more complex project. Additionally, I'm often the only PR reviewer, and my bandwidth is limited. While I still want to encourage beginners wherever I can (like via mentoring), I don't think contributions to qutebrowser (for non-users) are the right way.
=> Remove qutebrowser

README.md
Note that for Hacktoberfest, the `junior job` label gets temporarily renamed to `Hacktoberfest`: https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3AHacktoberfest
The other 11 months of the year, it's `junior job` however :)
=> Add Godot Engine, missing linebreak

README.md
Twitter's Util repo uses "good first commit" instead of "Starter" as a label.
Link and description fixed in the attached PR
=> Fix label tag for Twitter Util

README.md
The Operation Code link for Ruby points to their [old (and now archived) repo](https://github.com/OperationCode/operationcode_old_site).
Also changed the name to match the JS one (operationcode -> Operation Code).
=> Update operation code ruby link

README.md
Hello!  
I'm a maintainer for several OpenStreetMap related projects. Here are a few projects where we use a "good first issue" label for issues ideal for new contributors.
- [name-suggestion-index](https://github.com/osmlab/name-suggestion-index/labels/good%20first%20issue) _(label: good first issue)_ <br> Canonical common brand names for OpenStreetMap
- [iD](https://github.com/openstreetmap/iD/labels/good%20first%20issue) _(label: good first issue)_ <br> The easy-to-use OpenStreetMap editor in JavaScript.
=> Add name-suggestion-index and iD

README.md
We add issues for beginners and are happy to mentor new contributors through their first open source experiences.
=> Added opsdroid

README.md
We've moved the content of webdev.dartlang.org (site-webdev) to two new sites: dart.dev (site-www) and angulardart.dev (site-angulardart, which isn't ready for contributors at this time).
=> dartlang.org -> dart.dev; remove site-webdev

README.md
mcollective has been deprecated and is no longer under active development, so I removed this listing. I'll see if I can find another repo with labels that we have that would be appropriate for beginners and file a separate PR
=> maint: remove mcollective

README.md
According to the maintainers of apex, apex is not actively maintained anymore: https://github.com/apex/apex/issues/932
=> Removing apex from the list of go projects

CONTRIBUTING.md
Updated [`contributing guidelines`](https://github.com/MunGell/awesome-for-beginners/blob/master/CONTRIBUTING.md) to include the preferred format for links. As discussed [here](https://github.com/MunGell/awesome-for-beginners/pull/408#issuecomment-537577434)
```
```
```
```
=> Updated link format for contributing guidelines

README.md
I'm a maintainer for CockroachDB. We're moving away from using `E-easy` and prefer to tag things with `good first issue` now. Thanks for the great aggregation!
=> CockroachDB: update to use `good first issue`

README.md
Small fix for typo in the name. The contributing guidelines didn't mention anything against this, but let me know if it's not appropriate.
=> Fixes typo in wemake-python-styleguide's name

README.md
The C++ link was pointing to the C# header.
---
```
```
```
```
=> Fix ToC links

README.md
I Changed the .NET Section to Alphabetic Order because I think that It's easier to read.
=> Changed .NET Section to Alphabetic Order

README.md
The repository under 'Python' is no longer open for contributions as it is archived by the owner.
=> Removed archived repository: Concept-to-Clinic

README.md
httpexpect is a Go library for end-to-end HTTP API testing.
```
```
```
```
=> Add httpexpect

README.md
I was running around checking your awesome list, and noticed that FreeCodeCamp didn't have any issues listed.  However I could go look at the full issue list and see some first timer issues.
It turns out the link and tag this list was looking for was using "first timers welcome" but the FreeCodeCamp repo apparently has changed to "first timers only".
Rather than trying to send in an issue, I figured I'd just fix your list and try my first pull request.  Let me know if I've done anything wrong with this, or didn't follow the process below (I figured I'd get some passes since this is a existing link, and not a new link, so I maintained the current list order etc.)
Old Label:
New Label:
=> Updating FreeCodeCamp lable to currently used first timer tag

README.md
"Roc" was renamed to "Roc Toolkit", this PR updates the name and link.
=> Update Roc link

README.md
Jarvis now supports Linux, MacOs and Windows, not just linux.
*Just updating the description, not introducing a new repo*
```
[jarvis](https://github.com/sukeesh/Jarvis/labels/difficulty%2Fnewcomer) _(label: difficulty/newcomer)_ <br>A personal assistant for Linux, MacOs and Windows based on Command line Interface.
```
=> Update Jarvis description

README.md
It adds the [Killgrave](https://github.com/friendsofgo/killgrave) project which is actively maintained by [Friends of Go](https://github.com/friendsofgo) community members and some individual contributors.
cc/ @MunGell
=> Add Killgrave on Go section

README.md
Fixed C# osu! label since old one no longer works
```
```
```
```
=> Fixed C# osu! label

README.md
This adds `lxd` to the list of `go` projects.
For LXD we have issues we mark as `easy` which we will quite actively mentor new comers on.
In the past we've had a lot of students pick those as part of assignments and they can usually be achieved in just a few hours or days (dependent on existing Go and system experience).
```
```
```
```
=> Add `lxd` to `go` projects

README.md
The project is no longer supported by the developer according to his Github repo.
- [X ] I've read [contributing guidelines](https://github.com/MunGell/awesome-for-beginners/blob/master/CONTRIBUTING.md)
- [X ] This PR does not introduce duplicates to the list
(This part of the checklist doesn't apply to my pull request.)
```
```
```
```
=> Removing VPN@HOME from projects

README.md
Hi @MunGell,
thank you for maintaining this great collection of beginner-friendly repositories. To ease the start for beginners, MoveIt recently decided to introduce better-guided issues reserved for first-timers and labeled as "first-timer-only". We are an active and welcoming community and hope to help many new robotics enthusiasts getting started in the world of open-source robotics and motion planning :) Therefore, it would be great if you could add MoveIt to your list.
Thanks in advance!
Cheers,
Sebastian
```
```
```
- …
```
=> Adding Moveit

README.md
I suggest to add [jupyterlab-lsp](https://github.com/krassowski/jupyterlab-lsp) repository (which implements coding assistance for JupyterLab) where we maintain a list of issues dedicated to beginner contributors; our issues for beginners (`good first issue` and `documentation`):
- provide a description of what should be done (and what are the possible solutions)
- link to relevant parts of codebase
- are held for new contributors for at least two weeks since creation
We also a pretty detailed [`CONTRIBUTING.md`](https://github.com/krassowski/jupyterlab-lsp/blob/master/CONTRIBUTING.md) and as a co-maintainer I am willing to guide any newcomers. I added the project into Typescript category, although a sizeable portion includes a Python backend. It is not clear to me what we should do if a …
=> Suggest addition of jupyterlab-lsp

README.md
PrestoSQL was rebranded as Trino. See https://trino.io/blog/2020/12/27/announcing-trino.html
```
```
```
```
=> Rename Presto SQL to Trino

data.json
[sButtons](https://github.com/sButtons/sbuttons) repository is now archived and not accepting new PRs. This was the only repo under the CSS category so I am removing it.
=> Removed sButton because it's archived

data.json
I have noticed an issue: #1294, I have updated the hyperlink with a new GitHub hyperlink of discourse.
=> Fixed broken hyperlink of Discourse -- Issue: #1294 

data.json
The good first issue label in the Time to Leave repository has been changed from 'good-first-issue' to 'good first issue'
This PR reflects that change.
=> Update Time to Leave label

data.json
Closes #1349 which mentions that this Mailpile repository no longer has any issues as they are rewriting the code.
=> Remove Mailpile from data.json

data.json
Fixed subtle error in the hyperlink to the Kanister repository
=> Fix Kanister link in data.json

data.json
The repository has been inactive for nine months so I reckoned it should be taken off.
=> Removed inactive repo Binari from data.json

data.json
Two different spellings meant that two categories were being made for them.
This appeared in the categories section as:
I have normalised the capitalisation of the "Script" in TypeScript to fix this issue.
=> Cleaned up TypeScript category in data.json

data.json
This repo has been inactive for 8 months.
This one is a little surprising as there seems to be no announcement about development being stopped on this, despite the fact that Vercel is quite a big organisation (they made Next.js).
Someone did open an issue (vercel/hyper#8043) asking about development over two months ago but haven't had a reply yet.
=> Remove zeit (now vercel)/hyper for inactivity

data.json
Update the label name of the TiDB repository from "for-new-contributors" to "good first issue".
=> Update The TiDB label

data.json
Alda is written in Go for the majority of the codebase, it was converted to clojure long time ago.
=> convert alda to go project

data.json
Add [Devopness](https://github.com/devopness/devopness) an open-source repository with several opportunities to contribute components such as a System Design library and an SDK.
=> feat: add Devopness entry to the data

data.json
Their last appropriately labelled issue was closed in Feb 2020 which is somehow 5 years ago.
=> Removed Shouldly for a lack of appropriate issues

data.json
Some of the Python repos are not good starting points for beginners (any more at least). To keep the list clean I removed those repos from data.json that have too few recent activity or no beginner friendly issues. Or both.
I've put each removal in a separate commit so they may be cherry-picked easily.
=> Removed python repos that does not seem fit

.github/README-template.j2
In addition to this warning, added a tip on how to open a link in a new tab.
Resolves #1542
=> Add a warning in README-template.j2 - links open in the same tab

data.json
the label is "new contributor opportunity" not "good first issue" for this specific project.
here's the [link](https://github.com/openstreetmap/iD/labels/new%20contributor%20opportunity)
=> changed the label for iD project to the right one

data.json
This pull request addresses Issue #1639 by updating outdated repository references in the JavaScript section of `data.json`. The following changes were made for accuracy and consistency:
- Updated `reactjs.org` ➜ `react.dev`
- Updated `zeit/next.js` ➜ `vercel/next.js`
- Updated `mui-org/material-ui` ➜ `mui/material-ui`
- Updated `vue-router` ➜ `vuejs/router`
These updates help ensure that contributors are directed to the correct and actively maintained repositories. Let me know if anything needs adjustment. Thanks!
=> Fix outdated repository links in JavaScript section (#1639)
